### PR TITLE
linux support

### PR DESCRIPTION
**Pull request by dankinsoid**

### CODE REVIEW

**Comment by dankinsoid** [comment]
@Kuniwak check please)

**Comment by Kuniwak** [comment]
Thank you, @dankinsoid .

Sorry for my late reply. Looks good to me.

**Comment by dankinsoid** [comment]
@Kuniwak Hello!
Could you create a new tag for last updates?

**Comment by Kuniwak** [comment]
I shipped this by v2.0.0. Sorry for my late reply.

**Pull request merged**
